PREFIX ext:  <http://mu.semte.ch/vocabularies/ext/>
PREFIX arev: <http://mu.semte.ch/vocabularies/ext/annotation-review#>
PREFIX oa:   <http://www.w3.org/ns/oa#>
PREFIX eli:  <http://data.europa.eu/eli/ontology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dct:  <http://purl.org/dc/terms/>

SELECT
  ?expression
  ?conceptScheme
  ?concept
  ?creator
  (SAMPLE(?titel) AS ?titelBesluit)
  (SAMPLE(?datum) AS ?datumBesluit)
  (SAMPLE(?impact) AS ?impact)
  (COUNT(DISTINCT ?approveReview) AS ?positief)
  (COUNT(DISTINCT ?rejectReview) AS ?negatief)
WHERE {
  ?originalAnnotation a oa:Annotation ;
                      oa:hasTarget ?expression ;
                      oa:hasBody ?concept .

  ?expression a eli:Expression .

  OPTIONAL { ?expression eli:title ?titel }
  OPTIONAL { ?expression eli:date_publication ?datum }

  {
    ?concept skos:inScheme ?conceptScheme .
    FILTER (?conceptScheme != <http://mu.semte.ch/vocabularies/ext/impact>)
  }
  UNION
  {
    ?concept a ext:NoMatchFound .
    ?task prov:generated ?originalAnnotation ;
          dct:isPartOf ?job .
    ?job ext:codelist ?conceptScheme .
  }

  OPTIONAL {
    ?originalAnnotation oa:hasBody ?impactConcept .
    ?impactConcept skos:inScheme <http://mu.semte.ch/vocabularies/ext/impact> ;
                   skos:prefLabel ?impact .
  }

  OPTIONAL {
    ?activity prov:generated ?originalAnnotation ;
              prov:wasAssociatedWith ?creator .
  }

  OPTIONAL {
    ?approveReview a ext:ReviewAnnotation ;
                   oa:hasTarget ?originalAnnotation ;
                   oa:hasBody arev:approve .
  }
  OPTIONAL {
    ?rejectReview a ext:ReviewAnnotation ;
                  oa:hasTarget ?originalAnnotation ;
                  oa:hasBody arev:reject .
  }
}
GROUP BY ?expression ?conceptScheme ?concept ?creator
ORDER BY ?creator ?expression ?conceptScheme ?concept
LIMIT 100