PREFIX ext:  <http://mu.semte.ch/vocabularies/ext/>
PREFIX arev: <http://mu.semte.ch/vocabularies/ext/annotation-review#>
PREFIX oa:   <http://www.w3.org/ns/oa#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT
  ?expression
  ?subject
  ?predicate
  (SUBSTR(STR(?entity), 1, 500) AS ?entityText)
  (COUNT(DISTINCT ?approveReview) AS ?positief)
  (COUNT(DISTINCT ?rejectReview) AS ?negatief)
WHERE {
  ?originalAnnotation a oa:Annotation ;
                      oa:hasTarget ?target ;
                      oa:hasBody ?statement .

  ?target oa:hasSource ?expression .
  ?target oa:hasSelector ?selector .

  ?statement rdf:subject ?subject ;
             rdf:predicate ?predicate ;
             rdf:object ?entity .

  OPTIONAL {
    ?approveReview a ext:ReviewAnnotation ;
                   oa:hasTarget ?originalAnnotation ;
                   oa:hasBody arev:approve .
  }
  OPTIONAL {
    ?rejectReview a ext:ReviewAnnotation ;
                  oa:hasTarget ?originalAnnotation ;
                  oa:hasBody arev:reject .
  }
}
GROUP BY ?expression ?subject ?predicate ?entity
LIMIT 100