networks:
  debug:
    driver: bridge
    name: debug
services:
  identifier-frontend:
    ports:
      - "80:80"
    restart: "no"
  identifier-dashboard:
    ports:
      - "81:80"
  dispatcher:
    restart: "no"
    networks:
      - default
      - debug
  database:
    restart: "no"
    networks:
      - default
      - debug
  virtuoso:
    restart: "no"
    networks:
      - default
      - debug
  resource:
    restart: "no"
  file:
    restart: "no"
  vc-issuer:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:0.7.0
  migrations:
    restart: "no"
  deltanotifier:
    restart: "no"
  frontend-harvesting:
    restart: "no"
  oparl-to-eli:
    restart: "no"
  lokaal-beslist-consumer:
    restart: no
  decisions-ghent-filter:
    restart: no
  oslo-eli-transformer:
    restart: no