x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/sparql-parser:0.0.14
    volumes:
      - ./config/authorization:/config
      - ./data/authorization:/data
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.3.0
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./data/db:/data
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.27.1
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.4.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  project-scripts:
    image: semtech/simple-script-store:1.0.0
    volumes:
      - ./scripts/:/app/scripts/
    restart: "no"
  odrl-parser:
    image: lblod/odrl-parser-service:0.0.1
    volumes:
      - ./config/odrl-parser:/config
  decisions-ghent-consumer:
    image: lblod/delta-consumer:feature-initial-sync-with-virtuoso-dump
    environment:
      DCR_SERVICE_NAME: decisions-ghent-consumer
      DCR_CRON_PATTERN_DELTA_SYNC: 0 * * * * # Every hour
      DCR_SYNC_BASE_URL: https://lokaalbeslist-harvester-1.s.redhost.be/
      DCR_SYNC_FILES_PATH: /sync/besluiten/files
      DCR_SYNC_DATASET_SUBJECT: http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump
      DCR_INITIAL_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/decisions-ghent
      DCR_DELTA_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/deltaSync/decisions-ghent
      DCR_JOB_CREATOR_URI: http://data.lblod.info/services/id/decisions-ghent-consumer
      DCR_DISABLE_INITIAL_SYNC: true
      DCR_DISABLE_DELTA_INGEST: true
      DCR_INGEST_GRAPH: "http://mu.semte.ch/graphs/decisions/landing"
      DCR_BATCH_SIZE: 1000
    volumes:
      # - ./config/consumers/decisions-ghent/mapping:/config/mapping
      - ./config/consumers/decisions-ghent:/config/triples-dispatching/custom-dispatching
    labels:
      - logging=true
    restart: always
    logging: *default-logging