services:
  identifier:
    image: benfidlers/mu-identifier:1.10.3-arm64
  dispatcher:
    platform: linux/amd64
  virtuoso:
    platform: linux/arm64
  database:
    platform: linux/amd64
  deltanotifier:
    image: semtech/mu-delta-notifier:latest
    platform: linux/arm64
  oparl-to-eli:
    image: brechtvdv/mu-javascript-template:1.9.1
    platform: linux/arm64

