x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"}]'
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
      SESSION_COOKIE_SECURE: "true"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/sparql-parser:0.0.14
    environment:
      USE_ODRL_POLICY: "false"
      LISP_DYNAMIC_SPACE_SIZE: 8192
    volumes:
      - ./config/authorization:/config
      - ./config/odrl-parser:/odrl
      - ./data/authorization:/data
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.4.0-rc.1
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./data/db:/data
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.27.2
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.4.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  project-scripts:
    image: semtech/simple-script-store:1.0.0
    volumes:
      - ./scripts/:/app/scripts/
    restart: "no"
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    environment:
      MU_SPARQL_ENDPOINT: http://virtuoso:8890/sparql
    volumes:
      - ./config/migrations:/data/migrations
  deltanotifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  acmidm-login:
    image: lblod/acmidm-login-service:0.12.0
    environment:
      LOG_SINK_URL: "http://sink"
      MU_APPLICATION_AUTH_JWK_PRIVATE_KEY: /config/jwk_private_key.json
      MU_APPLICATION_AUTH_USERID_CLAIM: vo_id
      MU_APPLICATION_AUTH_ROLE_CLAIM: "abb_decide_rol_3d"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/bestuurseenheden-bestuursorganen"
      # The following are environment-specific and should be set in the
      # environment's appropriate override file.
      MU_APPLICATION_AUTH_CLIENT_ID: "<AUTH_CLIENT_ID>"
      MU_APPLICATION_AUTH_DISCOVERY_URL: "<AUTH_DISCOVERY_URL>"
      MU_APPLICATION_AUTH_REDIRECT_URI: "<AUTH_REDIRECT_URI>"
    volumes:
      - ./config/login:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  login:
    image: semtech/mu-login-service:3.0.0
    links:
      - database:database
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  sink:
    image: nginx:1.15.2
    volumes:
      - ./config/sink/sink.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend:
    image: lblod/frontend-decide:0.0.3
    environment:
      # The following are environment-specific and should be set in the
      # environment's appropriate override file.
      EMBER_OAUTH_API_KEY: "<OAUTH_API_KEY>"
      EMBER_OAUTH_API_REDIRECT_URL: "<OAUTH_API_REDIRECT_URL>"
      EMBER_OAUTH_API_BASE_URL: "<OAUTH_API_BASE_URL>"
      EMBER_OAUTH_API_LOGOUT_URL: "<OAUTH_API_LOGOUT_URL"
      EMBER_OAUTH_API_SCOPE: "<OAUTH_API_SCOPE>"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  ##############################################################################
  # DATA SPACE
  ##############################################################################
  dcat:
    image: lblod/dcat-service:0.0.1
  odrl-parser:
    image: lblod/odrl-parser-service:0.0.5
    volumes:
      - ./config/odrl-parser:/config
  vc-issuer:
    image: lblod/oid4vc-login-service:0.0.1
    environment:
      ISSUER_DID: did:web:example.com:some:did
      ISSUER_KEY_ID: did:web:example.com:some:did#somekey
      VERIFIER_DID: did:web:example.com:some:did
      VERIFIER_KEY_ID: did:web:example.com:some:did#id
      ISSUER_PUBLIC_KEY: notatallsecretkey
      ISSUER_PRIVATE_KEY: superultrasecretkey
      ISSUER_URL: https://example.com/vc-issuer
      VERIFIER_URL: https://example.com/vc-verifier
      LOGO_URL: https://example.com/assets/logo.png
      CREDENTIAL_TYPE: DecideCredential
      NO_DID_PREFIX: true
      SINGLE_CREDENTIAL_RESPONSE: true
    restart: always
    labels:
      - "logging=true"
      
 ##############################################################################
  # GENERIC PIPELINE COMPONENTS (USED IN OPARL, OSLO, PDF, AND AI PIPELINES)
  ##############################################################################
  frontend-harvesting:
    image: lblod/frontend-harvesting-self-service:feature-oparl-harvesting
    environment:
      EMBER_AUTHENTICATION_ENABLED: "true"
      EMBER_LOGIN_ROUTE: "login"
      EMBER_OPARL_HARVESTING_ENABLED: true
      EMBER_PDF_HARVESTING_ENABLED: true
      EMBER_OSLO_HARVESTING_ENABLED: true
      EMBER_NER_AND_NEL_ANNOTATIONS_ENABLED: true
      EMBER_CODELIST_MAPPING_ENABLED: true
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  job-controller:
    image: lblod/job-controller-service:1.2.0
    volumes:
      - ./config/job-controller:/config
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/harvesting"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  scheduled-job-controller:
    image: lblod/scheduled-job-controller-service:1.2.1
    environment:
      LOG_SPARQL_ALL: "false"
      DEBUG_AUTH_HEADERS: "false"
      MAX_CONCURRENT_JOBS: 3
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/harvesting"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  ##############################################################################
  # OPARL HARVESTING PIPELINE
  ##############################################################################
  harvest_diff:
    image: lblod/harvesting-diff-service:0.3.0
    environment:
      TARGET_GRAPH: "http://mu.semte.ch/graphs/harvesting"
      PUBLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
      LIMIT_SIZE: 2000
      LOGGING_LEVEL: "INFO"
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  harvest_sameas:
    image: lblod/import-with-sameas-service:4.8.0
    environment:
      RENAME_DOMAIN: "http://data.lblod.info/id/"
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public/freiburg"
      HIGH_LOAD_DATABASE_ENDPOINT: "http://virtuoso:8890/sparql"
      ROLLBACK_ENABLED: "false"
      TASK_TIMEOUT_HOURS: "20"
      LOG_SPARQL_ALL: "false"
      DEBUG_AUTH_HEADERS: "false"
    volumes:
      - ./config/same-as-service:/config
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  harvest_singleton-job:
    image: lblod/harvesting-singleton-job-service:1.0.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  oparl-to-eli:
    image: lblod/oparl-to-eli-service:0.0.3
    volumes:
      - ./config/oparl-to-eli/:/config/
      - ./data/files:/share
    environment:
      OPARL_ENDPOINT: "https://ris.freiburg.de/oparl"
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public/freiburg"

  ##############################################################################
  # GHENT DECISIONS PIPELINE
  ##############################################################################
  lokaal-beslist-consumer:
    image: lblod/decide-harvester-consumer-service:1.0.0
    environment:
      SYNC_BASE_URL: https://lokaalbeslist-harvester-1.s.redhost.be/ # Harvester 1 hosts Ghent decisions
      SYNC_FILES_PATH: /sync/besluiten/files
      SYNC_DATASET_SUBJECT: http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump
      LANDING_GRAPH: http://mu.semte.ch/graphs/oslo-decisions/landing
      BATCH_SIZE: 5000
      OPERATION_URI: http://lblod.data.gift/id/jobs/concept/TaskOperation/oslo-eli/consume
      HIGH_LOAD_DATABASE_ENDPOINT: http://virtuoso:8890/sparql
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  decisions-ghent-filter:
    image: lblod/decide-harvester-filter-service:1.0.0
    environment:
      INPUT_GRAPH: http://mu.semte.ch/graphs/oslo-decisions/landing
      BYPASS_MU_SPARQL_ENDPOINT: true
      BATCH_SIZE: 1000
      SLEEP_BETWEEN_BATCHES: 5
      OPERATION_URI: http://lblod.data.gift/id/jobs/concept/TaskOperation/oslo-eli/filter
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  oslo-eli-transformer:
    image: lblod/decide-harvester-transformation-service:1.0.0
    environment:
      INPUT_GRAPH: http://mu.semte.ch/graphs/oslo-decisions/landing
      OUTPUT_GRAPH: http://mu.semte.ch/graphs/public/gent
      ORGANIZATIONS_GRAPH: http://mu.semte.ch/graphs/bestuurseenheden-bestuursorganen
      BYPASS_MU_SPARQL_ENDPOINT: true
      BATCH_SIZE: 1000
      SLEEP_BETWEEN_BATCHES: 5
      OPERATION_URI: http://lblod.data.gift/id/jobs/concept/TaskOperation/oslo-eli/transform
    labels:
      - logging=true
    restart: always
    logging: *default-logging

  ##############################################################################
  # AI PIPELINES
  ##############################################################################
  entity-linking:
    image: lblod/entity-linking-service:latest
    environment:
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/harvesting"
      HIGH_LOAD_DATABASE_ENDPOINT: http://triplestore:8890/sparql
    links:
      - database:database
  pdf-scraper:
    image: semanticai/decide-pdf-scraper:0.0.1
    environment:
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  pdf-content:
    image: semanticai/decide-pdf-content-extraction:0.0.4
    environment:
      APACHE_TIKA_URL: "http://apache-tika:9998/tika"
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
      MOUNTED_SHARE_FOLDER: "/mnt/share"
    volumes:
      - ./data/files:/mnt/share
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  apache-tika:
    image: lblod/apache-tika-service:0.0.3
    restart: always
    logging: *default-logging

  question-answering:
    image: semanticai/decide-question-answering:0.0.0
    restart: always
    logging: *default-logging

  ##################################
  ### elastic and embeddings
  ##################################
  search:
    image: semtech/mu-search:feature-large-dense-vector
    ports:
      - "4000:80"
    volumes:
      - ./config/search:/config
  elasticsearch:
    image: semtech/mu-search-elastic-backend:feature-bump-es-9.2.0
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  embedding:
    image: semanticai/embedding-service:0.0.3
    labels:
      - logging=true
    environment:
      TZ: Europe/Brussels
      OLLAMA_HOST: "http://embedding-ollama:11434"
      LOG_SPARQL_ALL: "false"
    volumes:
      - ./config/embedding/config.py:/app/config.py
    depends_on:
      - embedding-ollama
  embedding-ollama:
    image: ollama/ollama:0.14.1
    volumes:
      - ./data/ollama:/root/.ollama
    command: serve && pull embeddinggemma:300m
    # in case you have an nvidia gpu available, like on our server
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
