networks:
  debug:
    driver: bridge
    name: debug
services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
    networks:
      - default
      - debug
  database:
    restart: "no"
    networks:
      - default
      - debug
  dcat:
    restart: "no"
  virtuoso:
    restart: "no"
    networks:
      - default
      - debug
  resource:
    restart: "no"
  file:
    restart: "no"
  odrl-parser:
    restart: "no"
  vc-issuer:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:0.7.0
  migrations:
    restart: "no"
  deltanotifier:
    restart: "no"
  frontend-harvesting:
    restart: "no"
  oparl-to-eli:
    restart: "no"
  lokaal-beslist-consumer:
    restart: no
  decisions-ghent-filter:
    restart: no
  oslo-eli-transformer:
    restart: no
  job-controller:
    restart: no
  harvest_diff:
    restart: no
  harvest_sameas:
    restart: no
  login:
    restart: no
  entity-linking:
    restart: "no"
