services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  resource:
    restart: "no"
  file:
    restart: "no"
  consumer-1:
    restart: no
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: 0 */5 * * * * # Every 5 minutes
      NODE_ENV: development