x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.11.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/sparql-parser:0.0.14
    volumes:
      - ./config/authorization:/config
      - ./data/authorization:/data
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: redpencil/virtuoso:1.3.0
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
      - ./data/db:/data
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.27.1
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.4.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  project-scripts:
    image: semtech/simple-script-store:1.0.0
    volumes:
      - ./scripts/:/app/scripts/
    restart: "no"
  dcat:
    image: lblod/dcat-service:0.0.1
  odrl-parser:
    image: lblod/odrl-parser-service:0.0.3
    volumes:
      - ./config/odrl-parser:/config
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
  vc-issuer:
    image: lblod/oid4vc-login-service:latest
    environment:
      ISSUER_DID: did:web:example.com:some:did
      ISSUER_KEY_ID: did:web:example.com:some:did#somekey
      VERIFIER_DID: did:web:example.com:some:did
      VERIFIER_KEY_ID: did:web:example.com:some:did#id
      ISSUER_PUBLIC_KEY: notatallsecretkey
      ISSUER_PRIVATE_KEY: superultrasecretkey
      ISSUER_URL: https://example.com/vc-issuer
      VERIFIER_URL: https://example.com/vc-verifier
      LOGO_URL: https://example.com/assets/logo.png
      CREDENTIAL_TYPE: DecideCredential
      NO_DID_PREFIX: true
      SINGLE_CREDENTIAL_RESPONSE: true
    restart: always
    labels:
      - "logging=true"
  deltanotifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  job-controller:
    image: lblod/job-controller-service:1.2.0
    volumes:
      - ./config/job-controller:/config
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/harvesting"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  harvest_diff:
    image: lblod/harvesting-diff-service:0.3.0
    environment:
      TARGET_GRAPH: "http://mu.semte.ch/graphs/harvesting"
      PUBLICATION_GRAPH: "http://mu.semte.ch/graphs/public"
      LIMIT_SIZE: 2000
      LOGGING_LEVEL: "INFO"
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging

  harvest_sameas:
    image: lblod/import-with-sameas-service:4.8.0
    environment:
      RENAME_DOMAIN: "http://data.lblod.info/id/"
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public"
      HIGH_LOAD_DATABASE_ENDPOINT: "http://virtuoso:8890/sparql"
      ROLLBACK_ENABLED: "false"
      TASK_TIMEOUT_HOURS: "20"
      LOG_SPARQL_ALL: "false"
      DEBUG_AUTH_HEADERS: "false"
    volumes:
      - ./config/same-as-service:/config
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  oparl-to-eli:
    image: lblod/oparl-to-eli-service:latest
    volumes:
      - ./config/oparl-to-eli/:/config/
      - ./data/files:/share
    environment:
      OPARL_ENDPOINT: "https://ris.freiburg.de/oparl"
      SUDO_QUERY_RETRY_FOR_HTTP_STATUS_CODES: "500"

  ################################################################################
  # GHENT DECISIONS PIPELINE
  ################################################################################
  lokaal-beslist-consumer:
    image: lblod/delta-consumer:feature-initial-sync-with-virtuoso-dump
    environment:
      DCR_SERVICE_NAME: lokaal-beslist-consumer
      DCR_SYNC_BASE_URL: https://lokaalbeslist-harvester-1.s.redhost.be/ # Harvester 1 hosts Ghent decisions
      DCR_SYNC_FILES_PATH: /sync/besluiten/files
      DCR_SYNC_DATASET_SUBJECT: http://data.lblod.info/datasets/delta-producer/dumps/lblod-harvester/BesluitenCacheGraphDump
      DCR_INITIAL_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/decisions-lokaal-beslist
      DCR_DELTA_SYNC_JOB_OPERATION: http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/deltaSync/decisions-ghent
      DCR_JOB_CREATOR_URI: http://data.lblod.info/services/id/decisions-ghent-consumer
      INGEST_GRAPH: http://mu.semte.ch/graphs/oslo-decisions/landing
      DCR_DISABLE_INITIAL_SYNC: true # Change in override
      DCR_DISABLE_DELTA_INGEST: true # Change in override
      BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: true
      DCR_BATCH_SIZE: 5000
      SLEEP_BETWEEN_BATCHES: 5
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  decisions-ghent-filter:
    image: lblod/decide-ghent-decisions-extraction-service
    environment:
      BATCH_SIZE: 1000
      SLEEP_BETWEEN_BATCHES: 5
      INPUT_GRAPH: http://mu.semte.ch/graphs/oslo-decisions/landing
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  oslo-eli-transformer:
    image: lblod/decide-oslo-to-eli-transformation-service
    environment:
      BATCH_SIZE: 100
      SLEEP_BETWEEN_BATCHES: 5
      INPUT_DECISION_RESOURCES_GRAPH: http://mu.semte.ch/graphs/oslo-decisions/ghent/besluit
      INPUT_DATA_GRAPH: http://mu.semte.ch/graphs/oslo-decisions/landing
      OUTPUT_GRAPH: http://mu.semte.ch/graphs/eli-decisions/ghent
    labels:
      - logging=true
    restart: always
    logging: *default-logging