PREFIX ext:  <http://mu.semte.ch/vocabularies/ext/>
PREFIX arev: <http://mu.semte.ch/vocabularies/ext/annotation-review#>
PREFIX oa:   <http://www.w3.org/ns/oa#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX eli:  <http://data.europa.eu/eli/ontology#>
PREFIX epvoc: <https://data.europarl.europa.eu/def/epvoc#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT
  ?expression
  (SAMPLE(?titel) AS ?titelBesluit)
  (SAMPLE(?datum) AS ?datumBesluit)
  ?subject
  ?predicate
  (SUBSTR(STR(?completeEntityText), 1, 500) AS ?entityText)
  (GROUP_CONCAT(distinct ?entityType ; SEPARATOR=", ") AS ?type)
  (GROUP_CONCAT(distinct ?linkedResource ; SEPARATOR=", ") AS ?linkedResource)
  ?creator
  (COUNT(DISTINCT ?approveReview) AS ?positief)
  (COUNT(DISTINCT ?rejectReview) AS ?negatief)
  (?municipalityLabel AS ?gemeente)
WHERE {
  ?originalAnnotation a oa:Annotation ;
                      oa:hasTarget ?target ;
                      oa:hasBody ?statement .

  ?target oa:hasSource ?expression .
  ?target oa:hasSelector ?selector .

  ?selector oa:start ?start ;
      oa:end ?end .
  
  ?expression a eli:Expression ;
    epvoc:expressionContent ?content ;
    ext:owningBody ?municipality .

  ?municipality a org:Organization ;
    skos:prefLabel ?municipalityLabel ;
    org:classification <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001> .  

  BIND(xsd:integer(?start) AS ?s)
  BIND(xsd:integer(?end) AS ?e)
  BIND(SUBSTR(?content, ?s + 1, ?e - ?s) AS ?completeEntityText)

  OPTIONAL { ?expression eli:title ?titel }
  OPTIONAL { ?expression eli:date_publication ?datum }

  ?statement rdf:subject ?subject ;
             rdf:predicate ?predicate ;
             rdf:object ?entity .

  OPTIONAL { ?entity a ?typeClass . }
  BIND(IF(BOUND(?typeClass), ?typeClass, DATATYPE(?entity)) AS ?entityType)

  OPTIONAL {
    ?linkStatement rdf:subject ?entity ;
                   rdf:predicate skos:exactMatch ;
                   rdf:object ?linkedResource .
  }

  ?activity prov:generated ?originalAnnotation ;
            prov:wasAssociatedWith ?creator .

  OPTIONAL {
    ?approveReview a ext:ReviewAnnotation ;
                   oa:hasTarget ?originalAnnotation ;
                   oa:hasBody arev:approve .
  }
  OPTIONAL {
    ?rejectReview a ext:ReviewAnnotation ;
                  oa:hasTarget ?originalAnnotation ;
                  oa:hasBody arev:reject .
  }
}
GROUP BY ?expression ?subject ?predicate ?completeEntityText ?creator ?municipalityLabel