PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX cms: <http://mu.semte.ch/vocabulary/cms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX eurovoc: <http://eurovoc.europa.eu/>
PREFIX ex: <http://example.org/>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ldes: <https://w3id.org/ldes#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>
PREFIX odrl: <https://www.w3.org/TR/odrl-vocab/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/catalogs/5d39120a-9575-41aa-b098-a63d6df99e6b>
      a dcat:Catalog;
      mu:uuid "5d39120a-9575-41aa-b098-a63d6df99e6b";
      dct:title "Example catalog";
      dct:description "A description";
      dct:issued "2025-10-16"^^xsd:date;
      dct:modified "2025-10-16"^^xsd:date;
      dct:language <http://publications.europa.eu/resource/authority/language/ENG>;
      dct:license ex:license;
      dct:rights ex:rights;
      dct:spatial ex:spatial;
      foaf:homepage ex:homepage;
      
      dct:publisher <http://data.lblod.info/id/agents/6887467a-f009-450d-8f03-df2e59f6e82c>;
      dcat:themeTaxonomy <http://data.lblod.info/id/concept-schemes/e8228abc-fce5-4f5e-82e6-7fba967a0d56>;
      dcat:record <http://data.lblod.info/id/catalog-records/e77be476-7373-4b69-8373-719236acd16a>;
      dcat:dataset <http://data.lblod.info/id/datasets/123e4567-e89b-12d3-a456-426614174000>;
      dcat:theme <http://data.lblod.info/id/concepts/6f6ec079-de02-4ae9-98dd-93c95ab049c2>;
      dcat:record <http://data.lblod.info/id/catalog-records/e77be476-7373-4b69-8373-719236acd16a>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://mu.semte.ch/ext/resources/publishers/0a99b381-636b-41c7-b387-a0376c1495ad>
      a ext:Publisher;
      mu:uuid "0a99b381-636b-41c7-b387-a0376c1495ad".
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://mu.semte.ch/cms/resources/pages/6d1a64ad-c639-4452-8d24-4c5672c85623>
      a <http://mu.semte.ch/vocabulary/cms/Page>;
      mu:uuid "6d1a64ad-c639-4452-8d24-4c5672c85623";
      dct:title "dct:title";
      cms:pageContent "cms:pageContent".
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/formats/a6a5b899-35f3-4194-aad7-9e35448bf43d>
      a dct:MediaTypeOrExtent;
      mu:uuid "a6a5b899-35f3-4194-aad7-9e35448bf43d";
      rdfs:label "format";
      dct:description "description of format";
      cms:page <http://mu.semte.ch/cms/resources/pages/6d1a64ad-c639-4452-8d24-4c5672c85623>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/agents/6887467a-f009-450d-8f03-df2e59f6e82c>
      a foaf:Agent;
      mu:uuid "6887467a-f009-450d-8f03-df2e59f6e82c".
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/concept-schemes/e8228abc-fce5-4f5e-82e6-7fba967a0d56>
      a skos:ConceptScheme;
      mu:uuid "e8228abc-fce5-4f5e-82e6-7fba967a0d56".
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    eurovoc:1234
      a skos:Concept;
      mu:uuid "fb3a92a8-4a15-4976-b231-2f9e350edeb6";
      skos:inScheme <http://data.lblod.info/id/concept-schemes/e8228abc-fce5-4f5e-82e6-7fba967a0d56>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/catalog-records/e77be476-7373-4b69-8373-719236acd16a>
      a dcat:CatalogRecord;
      mu:uuid "e77be476-7373-4b69-8373-719236acd16a";
      dct:title "Example catalog";
      dct:description "Example description";
      dct:issued "2025-10-16"^^xsd:date;
      dct:modified "2025-10-16"^^xsd:date;
      foaf:primaryTopic <http://data.lblod.info/id/datasets/123e4567-e89b-12d3-a456-426614174000>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/distributions/08a3c086-db07-458b-9a65-34064697503c>
      a dcat:Distribution;
      mu:uuid "08a3c086-db07-458b-9a65-34064697503c";
      dct:title "A distribution";
      dct:description "Distribution title";
      dct:issued "2025-10-16"^^xsd:date;
      dct:modified "2025-10-16"^^xsd:date;
      dct:license ex:license;
      dct:rights ex:rights;
      dcat:accessURL <https://example.org/access>;
      dcat:downloadURL <https://example.org/download>;
      dcat:mediaType ex:mediaType;
      dcat:byteSize 8;
      dct:format <http://data.lblod.info/id/formats/a6a5b899-35f3-4194-aad7-9e35448bf43d>.
  }
}
;
INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/datasets/123e4567-e89b-12d3-a456-426614174000>
      a dcat:Dataset;

      ##########################
      # Core DCAT-AP properties
      ##########################
      dct:title "Example Dataset Title"@en ;
      dct:description "A description of the dataset in English."@en ;
      dct:identifier "urn:uuid:123e4567-e89b-12d3-a456-426614174000" ;
      mu:uuid "123e4567-e89b-12d3-a456-426614174000" ;
      
      ##########################
      # From Data Space Protocol
      ##########################
      odrl:hasPolicy ex:odrl-policy-001 ;
      
      ########################
      # Recommended properties
      ########################
      dct:publisher <http://data.lblod.info/id/agents/6887467a-f009-450d-8f03-df2e59f6e82c>;
      dcat:distribution <http://data.lblod.info/id/distributions/08a3c086-db07-458b-9a65-34064697503c> ;
      dcat:keyword "climate"@en , "temperature"@en ;

      dcat:theme eurovoc:1234 ;  # Theme from a controlled vocabulary (e.g. EuroVoc)
      dct:spatial <http://publications.europa.eu/resource/authority/continent/EU> ;
      dct:temporal ex:temporal;
      dcat:contactPoint <http://data.lblod.info/id/agents/6887467a-f009-450d-8f03-df2e59f6e82c> ;
      
      dct:accessRights <http://publications.europa.eu/resource/authority/access-right/PUBLIC> ;
      dcat:landingPage <https://example.org/dataset/001> ;
      dct:accrualPeriodicity <http://publications.europa.eu/resource/authority/frequency/ANNUAL> ;

      ########################
      # Optional properties
      ########################
      dct:issued "2023-04-01"^^xsd:date ;
      dct:modified "2025-09-30"^^xsd:date ;
      dct:language <http://publications.europa.eu/resource/authority/language/ENG> ;
      dct:creator <http://data.lblod.info/id/agents/6887467a-f009-450d-8f03-df2e59f6e82c> ;
      dcat:version "1.2" ;
      dct:type <http://data.lblod.info/id/concepts/6f6ec079-de02-4ae9-98dd-93c95ab049c2> ;
      owl:versionInfo "Version 1.2 updated for schema compliance." ;
      adms:versionNotes "Minor update to metadata and schema."@en ;
      dct:provenance ex:provenance-001 ;
      # we should very much use this one to link to a shacl profile
      dct:conformsTo ex:standard-001 ;

      # Linking to itself
      dct:source <http://data.lblod.info/id/datasets/123e4567-e89b-12d3-a456-426614174000> ;
      dct:relation <http://data.lblod.info/id/datasets/123e4567-e89b-12d3-a456-426614174000> ;
      dct:isVersionOf <http://data.lblod.info/id/datasets/123e4567-e89b-12d3-a456-426614174000> ;
      dct:hasVersion <http://data.lblod.info/id/datasets/123e4567-e89b-12d3-a456-426614174000> ;

      dct:isReferencedBy ex:publication-002 ;
      prov:wasGeneratedBy ex:prov-activity-001 ;
      dcat:qualifiedAttribution [
        a prov:Attribution ;
        prov:agent <http://data.lblod.info/id/agents/6887467a-f009-450d-8f03-df2e59f6e82c> ;
        prov:hadRole <http://publications.europa.eu/resource/authority/role/AUTHOR>
      ] ;
      dcat:inSeries ex:dataset-series-001 ;
      adms:identifier [
        a adms:Identifier ;
        skos:notation "ABC-123" ;
        adms:schemaAgency "Example Agency"
      ] ;
      dcatap:applicableLegislation ex:legalResource-001 ;
      dct:accessRights ex:rightsStatement-001 ;
      adms:sample ex:sample-distribution-001 ;

      ################################
      # optionals we likely won't use
      ################################
      dcat:qualifiedRelation ex:relation-001 ;
      dcat:temporalResolution "P1Y"^^xsd:duration ;
      dcat:spatialResolutionInMeters 1
      foaf:page ex:foaf-document-001
    .

    ex:temporal
      a dct:PeriodOfTime ;
      dct:startDate "2021-01-01"^^xsd:date ;
      dct:endDate "2022-12-31"^^xsd:date
    .
  }
}
