PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX epvoc:   <https://data.europarl.europa.eu/def/epvoc#>
PREFIX prov: <http://www.w3.org/ns/prov#>

DELETE {
  GRAPH <http://mu.semte.ch/graphs/public/gent> {
   ?expr epvoc:expressionContent ?oldContent . 
  }
}
INSERT {
  GRAPH <http://mu.semte.ch/graphs/public/gent> {
   ?expr epvoc:expressionContent ?newAggrContentWithLang . 
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public/gent> {
  {
    SELECT ?expr (GROUP_CONCAT(?nummerAndValue; separator="\n") AS ?newAggrContent)
	  WHERE {
      {
        SELECT ?expr ?nummerAndValue
        WHERE {
          ?expr eli:has_part ?artikel .
          ?artikel eli:number ?nummer ;
                   prov:value ?value .
          BIND(concat(?nummer, '\n', ?value) as ?nummerAndValue)
        }
		    ORDER BY ?nummer
      }
    }
    GROUP BY ?expr
  }
  ?expr epvoc:expressionContent ?oldContent .
  BIND(strlang(?newAggrContent, 'nl') as ?newAggrContentWithLang) 
  }
}