PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/harvesting> {
    <http://data.lblod.info/ontology/airo#mistral-medium-3-5>
       ext:openrouterId "mistralai/mistral-medium-3-5" .
  }
}
