PREFIX eli: <http://data.europa.eu/eli/ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX epvoc:   <https://data.europarl.europa.eu/def/epvoc#>
PREFIX prov: <http://www.w3.org/ns/prov#>

INSERT {
  GRAPH <http://mu.semte.ch/graphs/public/gent> {
   ?expr epvoc:expressionContent ?fallbackContentWithLang . 
  }
}
WHERE {
  GRAPH <http://mu.semte.ch/graphs/public/gent> {
    ?expr a eli:Expression ;
        eli:title ?title .
    FILTER NOT EXISTS { 
        ?expr epvoc:expressionContent ?content . 
    }
    OPTIONAL {
        ?expr eli:description ?description .
    }
    BIND(strlang(if(bound(?description), str(?description), str(?title)), 'nl') as ?fallbackContentWithLang)
  }
}