x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '3'

services:
  ##############################################################################
  # AI PIPELINES
  ##############################################################################
  entity-linking:
    image: semanticai/entity-linking-backend:0.0.1
    environment:
      TARGET_GRAPH: 'http://mu.semte.ch/graphs/public'
      DEFAULT_GRAPH: 'http://mu.semte.ch/graphs/harvesting'
      ALLOW_MU_AUTH_SUDO: 'true'
      OLLAMA_HOST: 'http://ollama:11434'
      NOMINATIM_ENDPOINT: 'http://nominatim:8080/'
      MCP_SERVER_URL: 'http://localhost:80/mcp/sse'
      ENABLED_TOOLS: 'search_sparql_docs,execute_sparql_query,search_location'

      LLM_PROVIDER: 'mistral'
      LLM_MAX_RETRIES: 3
      MISTRAL_MODEL: 'ministral-14b-2512'
    links:
      - database:database
    volumes:
      - ./../config/nel/config:/config
      - ./../data/nel:/app/data
    restart: always
  pdf-scraper:
    image: semanticai/decide-pdf-scraper:0.0.3
    environment:
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  pdf-content:
    image: semanticai/decide-pdf-content-extraction:0.0.7
    environment:
      APACHE_TIKA_URL: 'http://apache-tika:9998/tika'
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
      MOUNTED_SHARE_FOLDER: '/mnt/share'
    volumes:
      - ./../data/files:/mnt/share
      - ./../config/pdf-content/config.json:/app/config.json:ro # Mount config as read-only
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  apache-tika:
    image: lblod/apache-tika-service:0.0.3
    restart: always
    logging: *default-logging

  question-answering:
    image: docker.io/semanticai/decide-question-answering:0.0.1
    environment:
      SEARCH_API_URL: 'http://search/expressions/large-search'
      LOG_SPARQL_ALL: 'false'
      EMBEDDING_API_URL: 'http://embedding/embed'
      MU_SPARQL_ENDPOINT: 'http://database:8890/sparql'
      MU_SPARQL_TIMEOUT: '30'
      GENERATION_PROVIDER: 'ollama'
      GENERATION_ENDPOINT: 'http://ollama:11434'
      GENERATION_MODEL: 'gemma3:1b'
      GENERATION_TIMEOUT: '300.0'
      MAX_CONTENT_CHARS: '1000'
      REQUEST_TIMEOUT: '10.0'
      ALLOW_MU_AUTH_SUDO: 'true'
    restart: always
    logging: *default-logging

  nominatim:
    image: mediagis/nominatim:5.1
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/belgium-latest.osm.pbf
    restart: always
    volumes:
      - ./../data/nominatim:/var/lib/postgresql/16/main

  named-entity-recognition:
    image: semanticai/decide-geocoding-service:0.0.2
    environment:
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
      CONFIG_PATH: /app/config.json
    volumes:
      - ./../config/ner/config.json:/app/config.json:ro # Mount config as read-only
    depends_on:
      - virtuoso
    labels:
      - logging=true
    restart: always
    logging: *default-logging

  ollama:
    image: ollama/ollama:0.21.2
    volumes:
      - ../data/ollama:/root/.ollama
    restart: always
    # in case you have an nvidia gpu available, like on our server
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    entrypoint:
      - /bin/sh
      - -c
      - ollama serve & pid=$$! && sleep 5 && ollama pull embeddinggemma && wait $$pid

  codelist-labeling:
    image: semanticai/codelist-labeling-service:0.0.1
    environment:
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
      NOMINATIM_ENDPOINT: http://nominatim:8080/
    restart: always
    volumes:
      - ./../config/codelist/config.json:/usr/src/app/config.json:ro # Mount config as read-only

