x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '3'

services:
  ##############################################################################
  # AI PIPELINES
  ##############################################################################
  entity-linking:
    image: local-entity-linking # TO UPDATE
    ports:
      - "81:80"
    environment:
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/harvesting"
      ALLOW_MU_AUTH_SUDO: "true"
      QDRANT_HOST: "qdrant"
      QDRANT_PORT: 6333
      OLLAMA_HOST: "http://ollama:11434"
      NOMINATIM_ENDPOINT: "http://nominatim:8080/"
      MCP_SERVER_URL: "http://localhost:80/mcp/sse"
      ENABLED_TOOLS: "search_sparql_docs,execute_sparql_query"
      
      LLM_PROVIDER: "mistral"
      LLM_MAX_RETRIES: 3
      MISTRAL_API_KEY: "SECRET_KEY"
      MISTRAL_MODEL: "ministral-14b-2512"
    links:
      - database:database
  pdf-scraper:
    image: local-scraper # TO UPDATE
    environment:
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting      
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  pdf-content:
    image: local-content # TO UPDATE
    environment:
      APACHE_TIKA_URL: "http://apache-tika:9998/tika"
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting      
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
      MOUNTED_SHARE_FOLDER: "/mnt/share"
    volumes:
      - ./../data/files:/mnt/share
      - ./../config/pdf-content/config.json:/app/config.json:ro  # Mount config as read-only
    labels:
      - logging=true
    restart: always
    logging: *default-logging
  apache-tika:
    image: lblod/apache-tika-service:0.0.3
    restart: always
    logging: *default-logging

  question-answering:
    image: docker.io/semanticai/decide-question-answering:0.0.0
    restart: always
    logging: *default-logging

  nominatim:
    image: mediagis/nominatim:5.1
    expose:
      - "8080:8080"
    environment:
      - PBF_URL=https://download.geofabrik.de/europe/belgium-latest.osm.pbf
    restart: unless-stopped
    volumes:
      - ./../data/nominatim:/var/lib/postgresql/16/main

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  named-entity-recognition:
    image: local-ner # TO UPDATE
    ports:
      - "8082:80"
    environment:
      TARGET_GRAPH: http://mu.semte.ch/graphs/harvesting
      JOB_GRAPH: http://mu.semte.ch/graphs/harvesting
      DATA_CONTAINER_GRAPH: http://mu.semte.ch/graphs/harvesting
      HARVEST_COLLECTIONS_GRAPH: http://mu.semte.ch/graphs/harvesting
      REMOTE_OBJECT_GRAPH: http://mu.semte.ch/graphs/harvesting
      FILES_GRAPH: http://mu.semte.ch/graphs/harvesting
      OPARL_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting
      OSLO_TEMP_GRAPH: http://mu.semte.ch/graphs/harvesting

      PUBLICATION_GRAPH: http://mu.semte.ch/graphs/public/pdf
      EXPRESSIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      WORKS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      MANIFESTATIONS_GRAPH: http://mu.semte.ch/graphs/public/pdf
      AI_GRAPH: http://mu.semte.ch/graphs/public/pdf
      ALLOW_MU_AUTH_SUDO: true
      CONFIG_PATH: /app/config.json
    volumes:
      - ./../config/ner/config.json:/app/config.json:ro  # Mount config as read-only
    depends_on:
      - virtuoso
    labels:
      - logging=true
    restart: always
    logging: *default-logging

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ../data/ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    entrypoint:
      - /bin/sh
      - -c
      - ollama serve & pid=$$! && sleep 5 && ollama pull embeddinggemma && wait $$pid
