services:
  dcat:
    image: lblod/dcat-service:0.0.1
  odrl-parser:
    image: lblod/odrl-parser-service:0.0.5
    volumes:
      - ../config/odrl-parser:/config
  vc-issuer:
    image: lblod/oid4vc-login-service:0.0.1
    environment:
      ISSUER_DID: did:web:example.com:some:did
      ISSUER_KEY_ID: did:web:example.com:some:did#somekey
      VERIFIER_DID: did:web:example.com:some:did
      VERIFIER_KEY_ID: did:web:example.com:some:did#id
      ISSUER_PUBLIC_KEY: notatallsecretkey
      ISSUER_PRIVATE_KEY: superultrasecretkey
      ISSUER_URL: https://example.com/vc-issuer
      VERIFIER_URL: https://example.com/vc-verifier
      LOGO_URL: https://example.com/assets/logo.png
      CREDENTIAL_TYPE: DecideCredential
      NO_DID_PREFIX: true
      SINGLE_CREDENTIAL_RESPONSE: true
    restart: always
    labels:
      - 'logging=true'
