x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '3'
services:
  acmidm-login:
    image: lblod/acmidm-login-service:0.12.0
    environment:
      LOG_SINK_URL: 'http://sink'
      MU_APPLICATION_AUTH_JWK_PRIVATE_KEY: /config/jwk_private_key.json
      MU_APPLICATION_AUTH_USERID_CLAIM: vo_id
      MU_APPLICATION_AUTH_ROLE_CLAIM: 'abb_decide_rol_3d'
      MU_APPLICATION_GRAPH: 'http://mu.semte.ch/graphs/bestuurseenheden-bestuursorganen'
      # The following are environment-specific and should be set in the
      # environment's appropriate override file.
      MU_APPLICATION_AUTH_CLIENT_ID: '<AUTH_CLIENT_ID>'
      MU_APPLICATION_AUTH_DISCOVERY_URL: '<AUTH_DISCOVERY_URL>'
      MU_APPLICATION_AUTH_REDIRECT_URI: '<AUTH_REDIRECT_URI>'
    volumes:
      - ../config/login:/config
    labels:
      - 'logging=true'
    restart: always
    logging: *default-logging
  login:
    image: semtech/mu-login-service:3.0.0
    links:
      - database:database
    environment:
      USERS_GRAPH: 'http://mu.semte.ch/graphs/users'
      SESSIONS_GRAPH: 'http://mu.semte.ch/graphs/sessions'
    restart: always
    logging: *default-logging
    labels:
      - 'logging=true'
