x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '3'
services:
  ##############################################################################
  # OPARL HARVESTING PIPELINE
  ##############################################################################
  harvest_diff:
    image: lblod/harvesting-diff-service:0.3.0
    environment:
      TARGET_GRAPH: 'http://mu.semte.ch/graphs/harvesting'
      PUBLICATION_GRAPH: 'http://mu.semte.ch/graphs/public'
      LIMIT_SIZE: 2000
      LOGGING_LEVEL: 'INFO'
    volumes:
      - ../data/files:/share
    labels:
      - 'logging=true'
    restart: always
    logging: *default-logging
  harvest_sameas:
    image: lblod/import-with-sameas-service:4.8.0
    environment:
      RENAME_DOMAIN: 'http://data.lblod.info/id/'
      TARGET_GRAPH: 'http://mu.semte.ch/graphs/public/freiburg'
      HIGH_LOAD_DATABASE_ENDPOINT: 'http://virtuoso:8890/sparql'
      ROLLBACK_ENABLED: 'false'
      TASK_TIMEOUT_HOURS: '20'
      LOG_SPARQL_ALL: 'false'
      DEBUG_AUTH_HEADERS: 'false'
    volumes:
      - ../config/same-as-service:/config
      - ../data/files:/share
    labels:
      - 'logging=true'
    restart: always
    logging: *default-logging
  harvest_singleton-job:
    image: lblod/harvesting-singleton-job-service:1.0.0
    labels:
      - 'logging=true'
    restart: always
    logging: *default-logging
  oparl-to-eli:
    image: lblod/oparl-to-eli-service:0.0.3
    volumes:
      - ../config/oparl-to-eli/:/config/
      - ../data/files:/share
    environment:
      OPARL_ENDPOINT: 'https://ris.freiburg.de/oparl'
      TARGET_GRAPH: 'http://mu.semte.ch/graphs/public/freiburg'
