x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '3'
services:
  report-generation:
    image: lblod/loket-report-generation-service:0.8.6-beta-8
    environment:
      DEFAULT_GRAPH: 'http://mu.semte.ch/graphs/reports'
      ONLY_KEEP_LATEST_REPORT: true
      RUN_REPORT_NOW: true
    volumes:
      - ../config/reports:/config
    restart: always
    labels:
      - logging=true
    logging: *default-logging
