x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: '10m'
    max-file: '3'
services:
  annotation-review:
    image: lblod/annotation-review-service:0.0.2
    restart: always
    labels:
      - logging=true
    logging: *default-logging
    environment:
      DEFAULT_MU_AUTH_SCOPE: 'http://services.semantic.works/annotation-review-service'
      TZ: Europe/Brussels
    volumes:
      - ../config/annotation-review:/config
  frontend-human-validator:
    image: lblod/frontend-decide-human-validator:0.0.7
    labels:
      - 'logging=true'
    restart: always
    logging: *default-logging
