(in-package :mu-cl-resources)

(define-resource catalog ()
  :class (s-prefix "dcat:Catalog")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:issued :string ,(s-prefix "dct:issued"))
                (:modified :string ,(s-prefix "dct:modified"))
                (:language :string ,(s-prefix "dct:language"))
                (:license :string ,(s-prefix "dct:license"))
                (:rights :string ,(s-prefix "dct:rights"))
                (:spatial :string ,(s-prefix "dct:spatial"))
                (:homepage :string ,(s-prefix "foaf:homepage")))
  :has-one `((agent :via ,(s-prefix "dct:publisher")
                        :as "publisher")
             (concept-scheme :via ,(s-prefix "dcat:themeTaxonomy")
                             :as "theme-taxonomy")
             (catalog-record :via ,(s-prefix "dcat:record")
                             :as "record"))
  :has-many `((dataset :via ,(s-prefix "dcat:dataset")
                       :as "datasets"))
  :features '(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/catalogs/")
  :on-path "catalogs")

(define-resource dataset ()
  :class (s-prefix "dcat:Dataset")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:issued :string ,(s-prefix "dct:issued"))
                (:modified :string ,(s-prefix "dct:modified"))
                (:identifier :string ,(s-prefix "dct:identifier"))
                (:keyword :string-set ,(s-prefix "dcat:keyword"))
                (:language :string ,(s-prefix "dct:language"))
                (:contact-point :string ,(s-prefix "dcat:contactPoint"))
                (:temporal :string ,(s-prefix "dct:temporal"))
                (:accrual-periodicity :string ,(s-prefix "dct:accrualPeriodicity"))
                (:landing-page :string ,(s-prefix "dcat:landingPage")))
  :features '(include-uri no-pagination-defaults)
  :has-one `((agent :via ,(s-prefix "dct:publisher")
                        :as "publisher")
             (catalog :via ,(s-prefix "dcat:dataset")
                      :inverse t
                      :as "catalog")
             (catalog-record :via ,(s-prefix "foaf:primaryTopic")
                             :inverse t
                             :as "primary-topic"))
  :has-many `((concept :via ,(s-prefix "dcat:theme")
                       :as "themes")
              (distribution :via ,(s-prefix "dcat:distribution")
                            :as "distributions")
              (data-service :via ,(s-prefix "dcat:servesDataset")
                            :inverse t
                            :as "data-services"))
  :resource-base (s-url "http://data.lblod.info/id/datasets/")
  :on-path "datasets")

(define-resource data-service ()
  :class (s-prefix "dcat:DataService")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:issued :datetime ,(s-prefix "dct:issued"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:endpoint-url :string ,(s-prefix "dcat:endpointURL"))
                (:conform-to :string ,(s-prefix "dct:conformsTo")))
  :features '(include-uri no-pagination-defaults)
  :has-one `((dataset :via ,(s-prefix "dcat:servesDataset")
                      :as "dataset"))
  :resource-base (s-url "http://data.lblod.info/id/data-services/")
  :on-path "data-services")

(define-resource distribution ()
  :class (s-prefix "dcat:Distribution")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:issued :string ,(s-prefix "dct:issued"))
                (:modified :string ,(s-prefix "dct:modified"))
                (:license :string ,(s-prefix "dct:license"))
                (:rights :string ,(s-prefix "dct:rights"))
                (:access-url :string ,(s-prefix "dcat:accessURL"))
                (:download-url :string ,(s-prefix "dcat:downloadURL"))
                (:media-type :string ,(s-prefix "dcat:mediaType"))
                (:byte-size :string ,(s-prefix "dcat:byteSize"))
                (:format :uri ,(s-prefix "dct:format")))
  :has-one `((dataset :via ,(s-prefix "dcat:distribution")
                      :inverse t
                      :as "dataset"))
  :features `(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/distributions/")
  :on-path "distributions")

(define-resource catalog-record ()
  :class (s-prefix "dcat:CatalogRecord")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:description :string ,(s-prefix "dct:description"))
                (:issued :string ,(s-prefix "dct:issued"))
                (:modified :string ,(s-prefix "dct:modified")))
  :has-one `((catalog :via ,(s-prefix "dcat:record")
                      :inverse t
                      :as "catalog")
             (dataset :via ,(s-prefix "foaf:primaryTopic")
                      :as "primary-topic"))
  :features `(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/catalog-records/")
  :on-path "catalog-records")

(define-resource concept ()
  :class (s-prefix "skos:Concept")
  :properties `((:pref-label :language-string-set ,(s-prefix "skos:prefLabel"))
                (:alt-label :language-string-set ,(s-prefix "skos:altLabel"))
                (:definition :language-string-set ,(s-prefix "skos:definition"))
                (:notation :number ,(s-prefix "skos:notation")))
  :has-many `((dataset :via ,(s-prefix "dcat:theme")
                       :inverse t
                       :as "datasets"))
  :has-one `((concept-scheme :via ,(s-prefix "skos:inScheme")
                             :as "concept-scheme"))
  :resource-base (s-url "http://data.lblod.info/id/concepts/")
  :features `(include-uri)
  :on-path "concepts")

(define-resource concept-scheme ()
  :class (s-prefix "skos:ConceptScheme")
  :properties `((:pref-label :string ,(s-prefix "skos:prefLabel"))
                (:show-in-hvt :boolean ,(s-prefix "ext:showInHVT")))
  :resource-base (s-url "http://data.lblod.info/id/concept-schemes/")
  :has-many `((catalog :via ,(s-prefix "dcat:themeTaxonomy")
                       :inverse t
                       :as "catalogs")
              (concept :via ,(s-prefix "skos:inScheme")
                       :inverse t
                       :as "concepts"))
  :features `(include-uri)
  :on-path "concept-schemes")

(define-resource agent ()
  :class (s-prefix "foaf:Agent")
  :properties `((:name :string ,(s-prefix "vcard:hasName"))
                (:email :string ,(s-prefix "vcard:hasEmail")))
  :features `(include-uri)
  :resource-base (s-url "http://data.lblod.info/id/agents/")
  :on-path "agents")

