(in-package :mu-cl-resources)

(define-resource activity ()
  :class (s-prefix "eli-dl:Activity")
  :properties `((:activity-label :string ,(s-prefix "eli-dl:activity_label"))
                (:meeting-state :string ,(s-prefix "oparl:meetingState"))
                (:cancelled :boolean ,(s-prefix "oparl:cancelled"))
                (:activity-start-date :datetime ,(s-prefix "eli-dl:activity_start_date"))
                (:activity-end-date :datetime ,(s-prefix "eli-dl:activity_end_date"))
                (:activity-order :number ,(s-prefix "eli-dl:activity_order"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted"))
                (:had-activity-type :url ,(s-prefix "eli-dl:had_activity_type")))
  :has-one `((location :via ,(s-prefix "vcard:hasLocality")
                       :as "has-locality"))
  :has-many `((organization :via ,(s-prefix "eli-dl:had_responsible_organization")
                            :as "had-responsible-organization")
              (person :via ,(s-prefix "eli-dl:had_participant_person")
                      :as "had-participant-person")
              (work :via ,(s-prefix "eli-dl:documented_by_a_realization_of")
                    :as "documented-by-a-realization-of")
              (work :via ,(s-prefix "eli-dl:recorded_in_a_realization_of")
                    :as "recorded-in-a-realization-of")
              (work :via ,(s-prefix "eli-dl:based_on_a_realization_of")
                    :as "based-on-a-realization-of")
              (foreseenActivity :via ,(s-prefix "eli-dl:consists_of")
                                :as "consists-of"))
  :resource-base (s-url "http://data.lblod.info/id/activities/")
  :features '(include-uri)
  :on-path "activities")

(define-resource legislativeProcessWork ()
  :class (s-prefix "eli-dl:LegislativeProcessWork")
  :has-one `((organization :via ,(s-prefix "eli-dl:legislative_process_work_creator")
                           :as "legislative-process-work-creator"))
  :resource-base (s-url "http://data.lblod.info/id/legislative-process-works/")
  :features '(include-uri)
  :on-path "legislative-process-works")

(define-resource parliamentaryTerm (organization)
  :class (s-prefix "eli-dl:ParliamentaryTerm")
  :resource-base (s-url "http://data.lblod.info/id/parliamentary-terms/")
  :features '(include-uri)
  :on-path "parliamentary-terms")

(define-resource participation ()
  :class (s-prefix "eli-dl:Participation")
  :properties `((:role :string ,(s-prefix "org:role"))
                (:voting-right :boolean ,(s-prefix "oparl:votingRight"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-one `((person :via ,(s-prefix "org:member")
                     :as "person")
             (organization :via ,(s-prefix "org:organization")
                           :as "organization")
             (temporal :via ,(s-prefix "org:memberDuring")
                       :as "temporal")
             (organization :via ,(s-prefix "oparl:onBehalfOf")
                           :as "on-behalf-of"))
  :resource-base (s-url "http://data.lblod.info/id/participations/")
  :features '(include-uri)
  :on-path "participations")

(define-resource foreseenActivity (activity)
  :class (s-prefix "eli-dl:ForeseenActivity")
  :properties `((:notation :number ,(s-prefix "skos:notation"))
                (:result :string ,(s-prefix "oparl:result")))
  :has-one `((activity :via ,(s-prefix "eli-dl:forms_part_of")
                       :as "forms-part-of"))
  :has-many `((work :via ,(s-prefix "eli-dl:based_on_a_realization_of")
                    :as "based-on-a-realization-of"))
  :resource-base (s-url "http://data.lblod.info/id/foreseen-activities/")
  :features '(include-uri)
  :on-path "foreseen-activities")
