(in-package :mu-cl-resources)

(define-resource work ()
  :class (s-prefix "eli:Work")
  :properties `((:expression-content :string ,(s-prefix "epvoc:expressionContent"))
                (:work-type :url ,(s-prefix "eli:work_type")))
  :has-many `((expression :via ,(s-prefix "eli:is_realized_by")
                          :as "is-realized-by"))
  :resource-base (s-url "http://data.lblod.info/id/works/"))

(define-resource expression ()
  :class (s-prefix "eli:Expression")
  :has-many `((manifestation :via ,(s-prefix "eli:is_embodied_by")
                             :as "is-embodied-by"))
  :resource-base (s-url "http://data.lblod.info/id/expressions/"))

(define-resource manifestation ()
  :class (s-prefix "eli:Manifestation")
  :properties `((:label :string ,(s-prefix "rdfs:label"))
                (:file-name :string ,(s-prefix "oparl:fileName"))
                (:media-type :string ,(s-prefix "eli:media_type"))
                (:issued :date ,(s-prefix "dcterms:issued"))
                (:byte-size :number ,(s-prefix "epvoc:byteSize"))
                (:is-exemplified-by :url ,(s-prefix "eli:is_exemplified_by"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-many `((activity :via ,(s-prefix "oparl:meeting")
                        :as "meetings")
              (foreseenActivity :via ,(s-prefix "oparl:agendaItem")
                                :as "agenda-items")
              (complexWork :via ,(s-prefix "eli:embodies")
                           :as "embodies"))
  :resource-base (s-url "http://data.lblod.info/id/manifestations/"))

(define-resource complexWork ()
  :class (s-prefix "eli:ComplexWork")
  :properties `((:title :string ,(s-prefix "eli:title"))
                (:identifier :string ,(s-prefix "dcterms:identifier"))
                (:date-document :date ,(s-prefix "eli:date_document"))
                (:work-type :url ,(s-prefix "eli:work_type"))
                (:consultation :url ,(s-prefix "oparl:consultation"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-one `((organization :via ,(s-prefix "eli:publisher")
                           :as "publisher"))
  :has-many `((complexWork :via ,(s-prefix "eli:refers_to")
                           :as "refers-to")
              (complexWork :via ,(s-prefix "eli:is_part_of")
                           :as "is-part-of")
              (complexWork :via ,(s-prefix "eli:has_part")
                           :as "has-part")
              (work :via ,(s-prefix "eli:has_member")
                    :as "has-member")
              (location :via ,(s-prefix "oparl:location")
                        :as "locations")
              (person :via ,(s-prefix "dcterms:creator")
                      :as "creators")
              (person :via ,(s-prefix "dcterms:contributor")
                      :as "contributors")
              (organization :via ,(s-prefix "dcterms:publisher")
                            :as "publishers")
              (organization :via ,(s-prefix "dcterms:creator")
                            :as "creators")
              (organization :via ,(s-prefix "dcterms:contributor")
                            :as "contributors"))
  :resource-base (s-url "http://data.lblod.info/id/complex-works/")
  :features '(include-uri)
  :on-path "complex-works")
