(define-resource organization ()
  :class (s-prefix "org:Organization")
  :properties `((:label :string ,(s-prefix "skos:prefLabel"))
                (:alternative-label :string ,(s-prefix "skos:altLabel"))
                (:website :url ,(s-prefix "oparl:website"))
                (:license :url ,(s-prefix "dct:license"))
                (:license-valid-since :datetime ,(s-prefix "oparl:licenseValidSince"))
                (:oparl-since :datetime ,(s-prefix "oparl:oparlSince"))
                (:identifier :string ,(s-prefix "dct:identifier"))
                (:see-also :url ,(s-prefix "rdfs:seeAlso"))
                (:agenda-item :url ,(s-prefix "oparl:agendaItem"))
                (:consultation :url ,(s-prefix "oparl:consultation"))
                (:file :url ,(s-prefix "oparl:file"))
                (:classification :string ,(s-prefix "org:classification"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted"))
                (:type :string ,(s-prefix "dct:type"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified")))
  :has-one `((organization :via ,(s-prefix "org:hasSubOrganization")
                           :as "sub-organization")
             (organization :via ,(s-prefix "org:subOrganizationOf")
                           :as "sub-organization-of")
             (temporal :via ,(s-prefix "dct:temporal")
                       :as "temporal")
             (location :via ,(s-prefix "oparl:location")
                       :as "location"))
  :has-many `((organizationContactPoint :via ,(s-prefix "schema:contactPoint")
                                        :as "contact-points")
              (person :via ,(s-prefix "oparl:person")
                      :as "people")
              (activity :via ,(s-prefix "eli-dl:had_responsible_organization")
                        :inverse t
                        :as "activities")
              (legislativeProcessWork :via ,(s-prefix "eli-dl:legislative_process_work_creator")
                                      :inverse t
                                      :as "legislative-process-works")
              (parliamentaryTerm :via ,(s-prefix "org:isLinkedTo")
                                 :as "parliamentary-terms")
              (membership :via ,(s-prefix "oparl:membership")
                          :as "memberships")
              (organization :via ,(s-prefix "oparl:externalBody")
                            :as "external-bodies"))
  :resource-base (s-url "http://data.lblod.info/id/organizations/")
  :features '(include-uri)
  :on-path "organizations")

(define-resource organizationContactPoint ()
  :properties `((:name :string ,(s-prefix "foaf:name"))
                (:email :string ,(s-prefix "schema:email"))))

(define-resource activity ()
  :class (s-prefix "eli-dl:Activity")
  :properties `((:name :string ,(s-prefix "eli-dl:activity_label"))
                (:meeting-state :string ,(s-prefix "oparl:meetingState"))
                (:cancelled :boolean ,(s-prefix "oparl:cancelled"))
                (:start :datetime ,(s-prefix "eli-dl:activity_start_date"))
                (:end :datetime ,(s-prefix "eli-dl:activity_end_date"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-one `((organization :via ,(s-prefix "eli-dl:had_responsible_organization")
                           :as "responsible-organization")
             (location :via ,(s-prefix "vcard:hasLocality")
                       :as "location"))
  :has-many `((organization :via ,(s-prefix "eli-dl:had_responsible_organization")
                            :as "responsible-organizations")
              (person :via ,(s-prefix "eli-dl:had_participant_person")
                      :as "participants")
              (work :via ,(s-prefix "eli-dl:documented_by_a_realization_of")
                           :as "documented-by-a-realization-of")
              (work :via ,(s-prefix "eli-dl:recorded_in_a_realization_of")
                           :as "recorded-in-a-realization-of")
              (work :via ,(s-prefix "eli-dl:based_on_a_realization_of")
                           :as "based-on-a-realization-of")
              (foreseenActivity :via ,(s-prefix "eli-dl:consists_of")
                                :as "consists-of"))
  :resource-base (s-url "http://data.lblod.info/id/activities/")
  :features '(include-uri)
  :on-path "activities")

(define-resource legislativeProcessWork ()
  :class (s-prefix "eli-dl:LegislativeProcessWork")
  :has-one `((organization :via ,(s-prefix "eli-dl:legislative_process_work_creator")
                           :as "legislative-process-work-creator"))
  :resource-base (s-url "http://data.lblod.info/id/legislative-process-works/")
  :features '(include-uri)
  :on-path "legislative-process-works")

(define-resource parliamentaryTerm (organization)
  :class (s-prefix "eli-dl:ParliamentaryTerm")
  :resource-base (s-url "http://data.lblod.info/id/parliamentary-terms/")
  :features '(include-uri)
  :on-path "parliamentary-terms")

(define-resource temporal ()
  :class (s-prefix "dct:PeriodOfTime")
  :properties `((:startDate :date ,(s-prefix "dcat:startDate"))
                (:endDate :date ,(s-prefix "dcat:endDate")))
  :resource-base (s-url "http://data.lblod.info/id/temporals/"))

(define-resource person ()
  :class (s-prefix "foaf:Person")
  :properties `((:full-name :string ,(s-prefix "rdfs:label"))
                (:family-name :string ,(s-prefix "foaf:familyName"))
                (:given-name :string ,(s-prefix "foaf:givenName"))
                (:form-of-address :string ,(s-prefix "oparl:formOfAddress"))
                (:affix :string ,(s-prefix "oparl:affix"))
                (:honorific-prefix :string ,(s-prefix "vcard:hasHonorificPrefix"))
                (:gender :url ,(s-prefix "vcard:hasGender"))
                (:phone :string ,(s-prefix "oparl:phone"))
                (:email :string ,(s-prefix "oparl:email"))
                (:status :string ,(s-prefix "oparl:status"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-one `((organization :via ,(s-prefix "oparl:body")
                           :as "body")
             (location :via ,(s-prefix "oparl:location")
                       :as "location"))
  :has-many `((membership :via ,(s-prefix "org:hasMembership")
                          :as "memberships"))
  :resource-base (s-url "http://data.lblod.info/id/people/")
  :features '(include-uri)
  :on-path "people")

(define-resource membership ()
  :class (s-prefix "org:Membership")
  :resource-base (s-url "http://data.lblod.info/id/memberships/")
  :features '(include-uri)
  :on-path "memberships")

(define-resource location ()
  :class (s-prefix "oparl:Location")
  :resource-base (s-url "http://data.lblod.info/id/locations/"))

(define-resource participation ()
  :class (s-prefix "eli-dl:Participation")
  :properties `((:role :string ,(s-prefix "org:role"))
                (:voting-right :boolean ,(s-prefix "oparl:votingRight"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-one `((person :via ,(s-prefix "org:member")
                     :as "person")
             (organization :via ,(s-prefix "org:organization")
                           :as "organization")
             (temporal :via ,(s-prefix "org:memberDuring")
                       :as "temporal")
             (organization :via ,(s-prefix "oparl:onBehalfOf")
                           :as "on-behalf-of"))
  :resource-base (s-url "http://data.lblod.info/id/participations/")
  :features '(include-uri)
  :on-path "participations")

(define-resource foreseenActivity ()
  :class (s-prefix "eli-dl:ForeseenActivity")
  :properties `((:number :number ,(s-prefix "skos:notation"))
                (:order :number ,(s-prefix "eli-dl:activity_order"))
                (:name :string ,(s-prefix "eli-dl:activity_label"))
                (:type :url ,(s-prefix "eli-dl:had_activity_type"))
                (:executed-in :url ,(s-prefix "eli-dl:was_executed_in"))
                (:result :string ,(s-prefix "oparl:result"))
                (:start :datetime ,(s-prefix "eli-dl:activity_start_date"))
                (:end :datetime ,(s-prefix "eli-dl:activity_end_date"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-one `((activity :via ,(s-prefix "eli-dl:forms_part_of")
                       :as "forms-part-of"))
  :has-many `((work :via ,(s-prefix "eli-dl:based_on_a_realization_of")
                    :as "based-on-a-realization-of"))
  :resource-base (s-url "http://data.lblod.info/id/foreseen-activities/")
  :features '(include-uri)
  :on-path "foreseen-activities")

(define-resource work ()
  :class (s-prefix "eli:Work")
  :properties `((:expression-content :string ,(s-prefix "epvoc:expressionContent"))
                (:work-type :url ,(s-prefix "eli:work_type")))
  :has-many `((expression :via ,(s-prefix "eli:is_realized_by")
                          :as "is-realized-by"))
  :resource-base (s-url "http://data.lblod.info/id/works/"))

(define-resource complexWork ()
  :class (s-prefix "eli:ComplexWork")
  :properties `((:title :string ,(s-prefix "eli:title"))
                (:identifier :string ,(s-prefix "dcterms:identifier"))
                (:date :date ,(s-prefix "eli:date_document"))
                (:work-type :url ,(s-prefix "eli:work_type"))
                (:consultation :url ,(s-prefix "oparl:consultation"))
                (:license :string ,(s-prefix "oparl:license"))
                (:keyword :string ,(s-prefix "oparl:keyword"))
                (:created :datetime ,(s-prefix "dct:created"))
                (:modified :datetime ,(s-prefix "dct:modified"))
                (:web :url ,(s-prefix "oparl:web"))
                (:deleted :boolean ,(s-prefix "oparl:deleted")))
  :has-one `((organization :via ,(s-prefix "eli:publisher")
                           :as "publisher"))
  :has-many `((complexWork :via ,(s-prefix "eli:refers_to")
                           :as "refers-to")
              (complexWork :via ,(s-prefix "eli:is_part_of")
                           :as "is-part-of")
              (complexWork :via ,(s-prefix "eli:has_part")
                           :as "has-part")
              (work :via ,(s-prefix "eli:has_member")
                    :as "has-member")
              (location :via ,(s-prefix "oparl:location")
                        :as "locations")
              (person :via ,(s-prefix "dcterms:creator")
                      :as "creators")
              (person :via ,(s-prefix "dcterms:contributor")
                      :as "contributors")
              (organization :via ,(s-prefix "dcterms:publisher")
                            :as "publishers")
              (organization :via ,(s-prefix "dcterms:creator")
                            :as "creators")
              (organization :via ,(s-prefix "dcterms:contributor")
                            :as "contributors"))
  :resource-base (s-url "http://data.lblod.info/id/complex-works/")
  :features '(include-uri)
  :on-path "complex-works")

(define-resource expression ()
  :class (s-prefix "eli:Expression")
  :has-many `((manifestation :via ,(s-prefix "eli:is_embodied_by")
                             :as "is-embodied-by"))
  :resource-base (s-url "http://data.lblod.info/id/expressions/"))

(define-resource manifestation ()
  :class (s-prefix "eli:Manifestation")
  :resource-base (s-url "http://data.lblod.info/id/manifestations/"))